export enum EFilterParam {
  district = 'district',
  typeKp = 'typeKp',
  headController = 'headController',
  substation = 'substation',
  channelType = 'channelType',
  channelCategory = 'channelCategory',
  typeWork = 'typeWork',
  executor = 'executor',
  dateStart = 'dateStart',
  dateEnd = 'dateEnd',
	inControl = 'inControl',
	objectType = 'objectType',
	page = 'page',
	limit = 'limit',
}
