import { IGenericResponseLogout, ISignInFields, IUserLogin } from './auth.interface'
import { IPropsCardControl } from './cardControl.interface'
import { IChangePassword } from './change-password.interface'
import { IChannelType } from './channel-type.interface'
import { IChannel } from './channel.interfaces'
import { IChannelCategory } from './channelCategory.interface'
import { IChannelEquipment } from './channelEquipment.intarface'
import { ICompletedWork, ICompletedWorkInfo, ICompletedWorkList } from './completed-work.interfaces'
import { ICompletedWorkYear } from './dashboard.interface'
import { IDistrict } from './district.interface'
import { IFile } from './file.interface'
import { IPropsForm } from './formProps.interface'
import { IGsmOperator } from './gsm-operator.interface'
import { IHeadController } from './head-controller.interface'
import { Ilog } from './log.interface'
import { IMeta } from './meta.interface'
import { IPropsMutation } from './mutation-data.interface'
import { IObjectType } from './objectType.interface'
import { IQueryParams } from './qparams.interface'
import { IRole } from './role.interface'
import { ISubstation, ISubstationInfo, ISubstationList } from './substation.interfaces'
import { ITelemechanicsDevices } from './telemechanicsDevice.interfaces'
import { ITypeKp } from './type-kp'
import { ITypeWork } from './typeWork.interface'
import { IUser, IUserDataLogin } from './user.interfaces'
import { IUserRole } from './userRole.interface'
import { IVoltageClass } from './voltage-class.interface'

export type { IChangePassword, IChannel, IChannelCategory, IChannelEquipment, IChannelType, ICompletedWork, ICompletedWorkInfo, ICompletedWorkList, ICompletedWorkYear, IDistrict, IFile, IGenericResponseLogout, IGsmOperator, IHeadController, Ilog, IMeta, IObjectType, IPropsCardControl, IPropsForm, IPropsMutation, IQueryParams, IRole, ISignInFields, ISubstation, ISubstationInfo, ISubstationList, ITelemechanicsDevices, ITypeKp, ITypeWork, IUser, IUserDataLogin, IUserLogin, IUserRole, IVoltageClass }
