import { IGenericResponseLogout, ISignInFields, IUserLogin } from './auth.interface'
import { IChangePassword } from './change-password.interface'
import { IChannelType } from './channel-type.interface'
import { IChannelCategory } from './channelCategory.interface'
import { ICompletedWork } from './completed-work.interface'
import { ICompletedWorkYear } from './dashboard.interface'
import { IDistrict } from './district.interface'
import { IFile } from './file.interface'
import { IGsmOperator } from './gsm-operator.interface'
import { IHeadController } from './head-controller.interface'
import { IMeta } from './meta.interface'
import { IPropsMutation } from './mutation-data.interface'
import { IQueryParams } from './qparams.interface'
import { IRole } from './role.interface'
import { IStatusAccount } from './status-account.interface'
import { ISubstation } from './substation.interface'
import { ITypeKp } from './type-kp'
import { IUser, IUserDataLogin } from './user'
import { IUserRole } from './userRole.interface'
import { IVoltageClass } from './voltage-class.interface'

export type { IChangePassword, IChannelType, ICompletedWork, IDistrict, IFile, IGenericResponseLogout, IGsmOperator, IHeadController, IMeta, IPropsMutation, IQueryParams, IRole, ISignInFields, IStatusAccount, ISubstation, ITypeKp, IUser, IUserDataLogin, IUserLogin, IUserRole, IVoltageClass, ICompletedWorkYear, IChannelCategory }
